Revert back to UD-1521 fsgroup behaviour and include runAsGroup
undistro/zora pull request #321
Opened 2024-11-06 00:20 UTC by knrc

## Description
Revert back to UD-1512 default behaviour and include runAsGroup in containers.

## Linked Issues

## How has this been tested?
- Deployed to local cluster
- Exec into job pod and check persistent volume permissions
- Exec into trivy plugin pod and check persistent volume permissions
- Check job and cronjob yaml to verify fsGroup and runAsGroup entries

## Checklist
- [X] I have labeled this PR with the relevant [Type labels](https://github.com/undistro/.github/labels?q=Type%3A)
- [ ] I have documented my code (if applicable)
- [ ] My changes are covered by tests

2024-11-06 13:25 UTC, matheusfm requested changes

2024-11-06 13:25 UTC, matheusfm commented on charts/zora/templates/plugins/trivy-job.yaml
> +                chgrp -R {{ .Values.scan.plugins.trivy.fsGroup }} /tmp/trivy-cache/* && chmod -R g+rwX /tmp/trivy-cache/*
Why do we need `chgrp` if both `fsGroup` and `runAsGroup` are already set ?

2024-11-06 14:22 UTC, knrc commented on charts/zora/templates/plugins/trivy-job.yaml
> +                chgrp -R {{ .Values.scan.plugins.trivy.fsGroup }} /tmp/trivy-cache/* && chmod -R g+rwX /tmp/trivy-cache/*
It shouldn't be necessary, but doesn't hurt to have it there.

2024-11-07 13:10 UTC, matheusfm approved these changes

2024-11-18 14:33 UTC, merged